describe('Test Case #1', () => {
  it('should handle the process of requesting and receiving a PDF report', () => {
    // ===== GIVEN PHASE =====
    cy.log('🔵 GIVEN: Given I have requested a PDF report from the Checklists and the report was successfully generated by the system');
    cy.log("GIVEN I navigate to the Facility Grid login page, enter the email, and submit the form");

    // Naviga alla pagina di login di Facility Grid
    cy.visit('https://loadtest.facilitygrid.net/login');

    // Inserisci l'email nel campo email
    cy.get('#user_login').clear().type('antonio.nuzzi@brilliantmachine.com.br');

    // Premi il pulsante di submit
    cy.get('#submit_btn').click();

    // Aspetta che il campo password si materializzi
    cy.get('#user_pass', { timeout: 10000 }).should('be.visible');

    // Inserisci la password nel campo password
    cy.get('#user_pass').type('@Nuzzi79FA');

    // Premi nuovamente il pulsante di submit
    cy.get('#submit_btn').click();

    // ===== WHEN PHASE =====
    cy.log('🟡 WHEN: When the system changes the report status to "Completed"');
    // Qui aggiungi il codice per verificare che lo stato del report sia cambiato in "Completed"

    // ===== THEN PHASE =====
    cy.log('🟢 THEN: Then I receive an email without attachment, with a message about XXhour expiration and a link to the General Generated Reports tab');
    // Qui aggiungi il codice per verificare che l'email sia stata ricevuta correttamente
  });
});